endpoint:
  address: mongodb://your.mongodb.address
  collection: your_collection_name
  database: your_database_name

metadata:
  key_0: value_0
  key_1: value_1
  environ: virtual
  backend: ovms_cpp
  device: CPU
  cpu-streams: 0
  grpc-workers: 0
  nireq: 0
